### ISSUE TITLE
Error: vyper: command not found

### ISSUE THREAD

**Issue by jaebooker** [truffle-box/vyper-example-box#2]
Keep getting this error, even though I have vyper installed.
![vypererror](https://user-images.githubusercontent.com/25276085/68928912-06b44400-0740-11ea-9c01-322154754175.png)

**Comment by jaebooker** [comment]
Vyper version
![Screen Shot 2019-11-15 at 12 37 56 AM](https://user-images.githubusercontent.com/25276085/68929017-3d8a5a00-0740-11ea-9222-11ebb2f9320f.png)

**Comment by onshop** [comment]
My fix on Ubuntu Vagrant VM was:

```
sudo apt install python3-pip
pip install vyper
```
I then had to edit my path in ~/.profile so truffle could find vyper:

`export PATH=$PATH:/home/vagrant/.local/bin`

After that the error was gone.

**Comment by cds-amal** [comment]
Closing this for issue maintenance.
